/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { CloudinaryVideo as CloudinaryVideo } from './components/cloudinary-video/cloudinary-video';

interface HTMLCloudinaryVideoElement extends CloudinaryVideo, HTMLElement {
}
declare var HTMLCloudinaryVideoElement: {
  prototype: HTMLCloudinaryVideoElement;
  new (): HTMLCloudinaryVideoElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "cloudinary-video": HTMLCloudinaryVideoElement;
  }
  interface ElementTagNameMap {
      "cloudinary-video": HTMLCloudinaryVideoElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "cloudinary-video": JSXElements.CloudinaryVideoAttributes;
      }
  }
  namespace JSXElements {
      export interface CloudinaryVideoAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          account?: string,
          width?: string,
          height?: string,
          alias?: string
      }
  }
}

import { MyName as MyName } from './components/my-name/my-name';

interface HTMLMyNameElement extends MyName, HTMLElement {
}
declare var HTMLMyNameElement: {
  prototype: HTMLMyNameElement;
  new (): HTMLMyNameElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-name": HTMLMyNameElement;
  }
  interface ElementTagNameMap {
      "my-name": HTMLMyNameElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-name": JSXElements.MyNameAttributes;
      }
  }
  namespace JSXElements {
      export interface MyNameAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          first?: string,
          last?: string
      }
  }
}

